# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\smartFarm_gui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QWidget(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.background.setStyleSheet("background-color: rgb(35, 44, 53);")
        self.background.setObjectName("background")
        self.navigation_bar = QtWidgets.QWidget(self.background)
        self.navigation_bar.setGeometry(QtCore.QRect(0, 0, 800, 67))
        self.navigation_bar.setStyleSheet("background-color: rgb(128, 160, 193);")
        self.navigation_bar.setObjectName("navigation_bar")
        self.widget = QtWidgets.QWidget(self.navigation_bar)
        self.widget.setGeometry(QtCore.QRect(12, 13, 441, 43))
        self.widget.setStyleSheet("background-image: url(:/Texts/images_backup/7inch_title.png);")
        self.widget.setObjectName("widget")
        self.controlMenu = QtWidgets.QPushButton(self.navigation_bar)
        self.controlMenu.setGeometry(QtCore.QRect(480, 0, 81, 71))
        self.controlMenu.setObjectName("controlMenu")
        self.dataMenu = QtWidgets.QPushButton(self.navigation_bar)
        self.dataMenu.setGeometry(QtCore.QRect(560, 0, 81, 71))
        self.dataMenu.setObjectName("dataMenu")
        self.graphMenu = QtWidgets.QPushButton(self.navigation_bar)
        self.graphMenu.setGeometry(QtCore.QRect(640, 0, 81, 71))
        self.graphMenu.setObjectName("graphMenu")
        self.cameraMenu = QtWidgets.QPushButton(self.navigation_bar)
        self.cameraMenu.setGeometry(QtCore.QRect(720, 0, 81, 71))
        self.cameraMenu.setObjectName("cameraMenu")
        self.stackedWidget = QtWidgets.QStackedWidget(self.background)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 70, 800, 413))
        self.stackedWidget.setObjectName("stackedWidget")
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.label = QtWidgets.QLabel(self.startPage)
        self.label.setGeometry(QtCore.QRect(130, 60, 551, 41))
        font = QtGui.QFont()
        font.setFamily("NanumSquare")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.connectButton = QtWidgets.QPushButton(self.startPage)
        self.connectButton.setGeometry(QtCore.QRect(160, 220, 501, 101))
        self.connectButton.setStyleSheet("background-color: rgb(81, 163, 0);\n"
"font: 18pt \"NanumSquare\";")
        self.connectButton.setObjectName("connectButton")
        self.stackedWidget.addWidget(self.startPage)
        self.error = QtWidgets.QWidget()
        self.error.setObjectName("error")
        self.connectButton_2 = QtWidgets.QPushButton(self.error)
        self.connectButton_2.setGeometry(QtCore.QRect(160, 220, 501, 101))
        self.connectButton_2.setStyleSheet("background-color: rgb(81, 163, 0);\n"
"font: 18pt \"NanumSquare\";")
        self.connectButton_2.setObjectName("connectButton_2")
        self.label_2 = QtWidgets.QLabel(self.error)
        self.label_2.setGeometry(QtCore.QRect(130, 60, 551, 41))
        font = QtGui.QFont()
        font.setFamily("NanumSquare")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(213, 0, 3);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.error)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.ui_widget = QtWidgets.QWidget(self.page)
        self.ui_widget.setGeometry(QtCore.QRect(210, 10, 553, 363))
        self.ui_widget.setStyleSheet("background-image:url(:/Widget/images_backup/fisrt_ui.png)")
        self.ui_widget.setObjectName("ui_widget")
        self.red_bulb = QtWidgets.QWidget(self.ui_widget)
        self.red_bulb.setGeometry(QtCore.QRect(251, 45, 67, 81))
        self.red_bulb.setStyleSheet("background-image: url(:/icon/images_backup/67x81_red_bulb.png);")
        self.red_bulb.setObjectName("red_bulb")
        self.green_bulb = QtWidgets.QWidget(self.ui_widget)
        self.green_bulb.setGeometry(QtCore.QRect(357, 45, 67, 81))
        self.green_bulb.setStyleSheet("background-image: url(:/icon/images_backup/67x81_green_bulb.png);")
        self.green_bulb.setObjectName("green_bulb")
        self.white_bulb = QtWidgets.QWidget(self.ui_widget)
        self.white_bulb.setGeometry(QtCore.QRect(462, 45, 67, 81))
        self.white_bulb.setStyleSheet("background-image: url(:/icon/images_backup/67x81_white_bulb.png);")
        self.white_bulb.setObjectName("white_bulb")
        self.redButton = QtWidgets.QPushButton(self.page)
        self.redButton.setGeometry(QtCore.QRect(95, 26, 117, 46))
        self.redButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.redButton.setStyleSheet("background-image: url(:/icon/images_backup/117x46_on_button.png);\n"
"border : none;")
        self.redButton.setText("")
        self.redButton.setFlat(False)
        self.redButton.setObjectName("redButton")
        self.greenButton = QtWidgets.QPushButton(self.page)
        self.greenButton.setGeometry(QtCore.QRect(95, 94, 117, 46))
        self.greenButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.greenButton.setStyleSheet("background-image: url(:/icon/images_backup/117x46_on_button.png);\n"
"border : none;")
        self.greenButton.setText("")
        self.greenButton.setFlat(False)
        self.greenButton.setObjectName("greenButton")
        self.whiteButton = QtWidgets.QPushButton(self.page)
        self.whiteButton.setGeometry(QtCore.QRect(95, 162, 117, 46))
        self.whiteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.whiteButton.setStyleSheet("background-image: url(:/icon/images_backup/117x46_on_button.png);\n"
"border : none;")
        self.whiteButton.setText("")
        self.whiteButton.setFlat(False)
        self.whiteButton.setObjectName("whiteButton")
        self.humiLabel = QtWidgets.QLabel(self.page)
        self.humiLabel.setGeometry(QtCore.QRect(95, 295, 117, 33))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(20)
        self.humiLabel.setFont(font)
        self.humiLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.humiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.humiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.humiLabel.setObjectName("humiLabel")
        self.tempLabel = QtWidgets.QLabel(self.page)
        self.tempLabel.setGeometry(QtCore.QRect(95, 348, 117, 33))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(20)
        self.tempLabel.setFont(font)
        self.tempLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.tempLabel.setTextFormat(QtCore.Qt.AutoText)
        self.tempLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel.setObjectName("tempLabel")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tempView = PlotWidget(self.page_3)
        self.tempView.setGeometry(QtCore.QRect(20, 70, 361, 291))
        self.tempView.setObjectName("tempView")
        self.humiView = PlotWidget(self.page_3)
        self.humiView.setGeometry(QtCore.QRect(410, 70, 361, 291))
        self.humiView.setObjectName("humiView")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.widget_2 = QtWebEngineWidgets.QWebEngineView(self.page_4)
        self.widget_2.setGeometry(QtCore.QRect(140, 10, 520, 390))
        self.widget_2.setObjectName("widget_2")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.controlMenu.setText(_translate("MainWindow", "Control"))
        self.dataMenu.setText(_translate("MainWindow", "Data"))
        self.graphMenu.setText(_translate("MainWindow", "Graph"))
        self.cameraMenu.setText(_translate("MainWindow", "Camera"))
        self.label.setText(_translate("MainWindow", "Welcome to Smartfarm - ESC"))
        self.connectButton.setText(_translate("MainWindow", "Connect to Smartfarm"))
        self.connectButton_2.setText(_translate("MainWindow", "Reconnect"))
        self.label_2.setText(_translate("MainWindow", "ERROR: Invaild Connection"))
        self.humiLabel.setText(_translate("MainWindow", "99%"))
        self.tempLabel.setText(_translate("MainWindow", "99°C"))

from PyQt5 import QtWebEngineWidgets
from pyqtgraph import PlotWidget
import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

