# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\smartFarm_gui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(205, 255, 236);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.loadnstart = QtWidgets.QStackedWidget(self.centralwidget)
        self.loadnstart.setObjectName("loadnstart")
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.startPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.startPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(50, 50))
        self.connectButton.setMaximumSize(QtCore.QSize(500, 30))
        self.connectButton.setStyleSheet("background-color: rgb(177, 170, 154);\n"
"font: 25 13pt \"NanumSquare\";")
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_2.addWidget(self.connectButton, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 1, 1, 1)
        self.debugButton = QtWidgets.QPushButton(self.startPage)
        self.debugButton.setAutoFillBackground(False)
        self.debugButton.setStyleSheet("font: 22pt \"NanumSquare\";")
        self.debugButton.setCheckable(False)
        self.debugButton.setChecked(False)
        self.debugButton.setAutoRepeat(False)
        self.debugButton.setAutoDefault(False)
        self.debugButton.setDefault(False)
        self.debugButton.setFlat(True)
        self.debugButton.setObjectName("debugButton")
        self.gridLayout_2.addWidget(self.debugButton, 1, 1, 1, 1)
        self.loadnstart.addWidget(self.startPage)
        self.errorPage = QtWidgets.QWidget()
        self.errorPage.setObjectName("errorPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.errorPage)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 5, 1, 1, 1)
        self.restartButton = QtWidgets.QPushButton(self.errorPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartButton.sizePolicy().hasHeightForWidth())
        self.restartButton.setSizePolicy(sizePolicy)
        self.restartButton.setMinimumSize(QtCore.QSize(50, 50))
        self.restartButton.setMaximumSize(QtCore.QSize(500, 30))
        self.restartButton.setStyleSheet("background-color: rgb(177, 170, 154);\n"
"font: 25 13pt \"NanumSquare\";")
        self.restartButton.setObjectName("restartButton")
        self.gridLayout_3.addWidget(self.restartButton, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 4, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.errorPage)
        self.label_2.setStyleSheet("font: 22pt \"NanumSquare\";")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 1, 1, 2)
        self.loadnstart.addWidget(self.errorPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.mainPage)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.menuFrame = QtWidgets.QFrame(self.mainPage)
        self.menuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.menuFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 0, 2, 1, 1)
        self.menuBackground = QtWidgets.QFrame(self.menuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBackground.sizePolicy().hasHeightForWidth())
        self.menuBackground.setSizePolicy(sizePolicy)
        self.menuBackground.setMinimumSize(QtCore.QSize(0, 0))
        self.menuBackground.setMaximumSize(QtCore.QSize(16777204, 60))
        self.menuBackground.setStyleSheet("background-color: rgb(204, 144, 168);")
        self.menuBackground.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuBackground.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBackground.setObjectName("menuBackground")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menuBackground)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlButton = QtWidgets.QPushButton(self.menuBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.controlButton.sizePolicy().hasHeightForWidth())
        self.controlButton.setSizePolicy(sizePolicy)
        self.controlButton.setStyleSheet("font: 25 16pt \"NanumSquare\";")
        self.controlButton.setCheckable(False)
        self.controlButton.setAutoRepeat(False)
        self.controlButton.setAutoExclusive(False)
        self.controlButton.setAutoDefault(False)
        self.controlButton.setDefault(True)
        self.controlButton.setFlat(True)
        self.controlButton.setObjectName("controlButton")
        self.horizontalLayout.addWidget(self.controlButton)
        self.statusButton = QtWidgets.QPushButton(self.menuBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.statusButton.sizePolicy().hasHeightForWidth())
        self.statusButton.setSizePolicy(sizePolicy)
        self.statusButton.setStyleSheet("font: 25 16pt \"NanumSquare\";")
        self.statusButton.setDefault(True)
        self.statusButton.setFlat(True)
        self.statusButton.setObjectName("statusButton")
        self.horizontalLayout.addWidget(self.statusButton)
        self.graphButton = QtWidgets.QPushButton(self.menuBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphButton.sizePolicy().hasHeightForWidth())
        self.graphButton.setSizePolicy(sizePolicy)
        self.graphButton.setStyleSheet("font: 25 16pt \"NanumSquare\";")
        self.graphButton.setDefault(True)
        self.graphButton.setFlat(True)
        self.graphButton.setObjectName("graphButton")
        self.horizontalLayout.addWidget(self.graphButton)
        self.cameraButton = QtWidgets.QPushButton(self.menuBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cameraButton.sizePolicy().hasHeightForWidth())
        self.cameraButton.setSizePolicy(sizePolicy)
        self.cameraButton.setStyleSheet("font: 25 16pt \"NanumSquare\";")
        self.cameraButton.setDefault(True)
        self.cameraButton.setFlat(True)
        self.cameraButton.setObjectName("cameraButton")
        self.horizontalLayout.addWidget(self.cameraButton)
        self.gridLayout_7.addWidget(self.menuBackground, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem11, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.menuFrame, 1, 0, 1, 2)
        self.mainFarm = QtWidgets.QStackedWidget(self.mainPage)
        self.mainFarm.setObjectName("mainFarm")
        self.controlPage = QtWidgets.QWidget()
        self.controlPage.setObjectName("controlPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.controlPage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.blueLabel = QtWidgets.QLabel(self.controlPage)
        self.blueLabel.setStyleSheet("font: 25 14pt \"NanumSquare\";")
        self.blueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.blueLabel.setObjectName("blueLabel")
        self.gridLayout_5.addWidget(self.blueLabel, 5, 0, 1, 1)
        self.redLabel = QtWidgets.QLabel(self.controlPage)
        self.redLabel.setStyleSheet("font: 25 14pt \"NanumSquare\";")
        self.redLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.redLabel.setObjectName("redLabel")
        self.gridLayout_5.addWidget(self.redLabel, 3, 0, 1, 1)
        self.blueSlider = QtWidgets.QSlider(self.controlPage)
        self.blueSlider.setMaximum(255)
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName("blueSlider")
        self.gridLayout_5.addWidget(self.blueSlider, 5, 1, 1, 1)
        self.redSlider = QtWidgets.QSlider(self.controlPage)
        self.redSlider.setMaximum(255)
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName("redSlider")
        self.gridLayout_5.addWidget(self.redSlider, 3, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem13, 2, 0, 1, 5)
        self.whiteLabel = QtWidgets.QLabel(self.controlPage)
        self.whiteLabel.setStyleSheet("font: 25 14pt \"NanumSquare\";")
        self.whiteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.whiteLabel.setObjectName("whiteLabel")
        self.gridLayout_5.addWidget(self.whiteLabel, 4, 0, 1, 1)
        self.whiteSlider = QtWidgets.QSlider(self.controlPage)
        self.whiteSlider.setMaximum(255)
        self.whiteSlider.setOrientation(QtCore.Qt.Horizontal)
        self.whiteSlider.setObjectName("whiteSlider")
        self.gridLayout_5.addWidget(self.whiteSlider, 4, 1, 1, 1)
        self.controlFrame = QtWidgets.QFrame(self.controlPage)
        self.controlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlFrame.setObjectName("controlFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.controlFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.controlLabel = QtWidgets.QLabel(self.controlFrame)
        font = QtGui.QFont()
        font.setFamily("NanumSquare")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.controlLabel.setFont(font)
        self.controlLabel.setStyleSheet("")
        self.controlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlLabel.setObjectName("controlLabel")
        self.gridLayout_6.addWidget(self.controlLabel, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.controlFrame, 0, 0, 1, 5)
        self.redButton = QtWidgets.QPushButton(self.controlPage)
        self.redButton.setObjectName("redButton")
        self.gridLayout_5.addWidget(self.redButton, 3, 2, 1, 1)
        self.whiteButton = QtWidgets.QPushButton(self.controlPage)
        self.whiteButton.setObjectName("whiteButton")
        self.gridLayout_5.addWidget(self.whiteButton, 4, 2, 1, 1)
        self.blueButton = QtWidgets.QPushButton(self.controlPage)
        self.blueButton.setObjectName("blueButton")
        self.gridLayout_5.addWidget(self.blueButton, 5, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem14, 6, 0, 1, 3)
        self.mainFarm.addWidget(self.controlPage)
        self.statusPage = QtWidgets.QWidget()
        self.statusPage.setObjectName("statusPage")
        self.mainFarm.addWidget(self.statusPage)
        self.gridLayout_4.addWidget(self.mainFarm, 0, 0, 1, 1)
        self.loadnstart.addWidget(self.mainPage)
        self.gridLayout.addWidget(self.loadnstart, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.loadnstart.setCurrentIndex(0)
        self.mainFarm.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect to Device"))
        self.debugButton.setText(_translate("MainWindow", "Welcome To SmartFarm"))
        self.restartButton.setText(_translate("MainWindow", "Reconnect"))
        self.label_2.setText(_translate("MainWindow", "ERROR: Invaild Connection"))
        self.controlButton.setText(_translate("MainWindow", "Control"))
        self.statusButton.setText(_translate("MainWindow", "Status"))
        self.graphButton.setText(_translate("MainWindow", "Graph"))
        self.cameraButton.setText(_translate("MainWindow", "Web Cam"))
        self.blueLabel.setText(_translate("MainWindow", "BLUE"))
        self.redLabel.setText(_translate("MainWindow", "RED"))
        self.whiteLabel.setText(_translate("MainWindow", "WHITE"))
        self.controlLabel.setText(_translate("MainWindow", "Control Menu"))
        self.redButton.setText(_translate("MainWindow", "0"))
        self.whiteButton.setText(_translate("MainWindow", "0"))
        self.blueButton.setText(_translate("MainWindow", "0"))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
